before:
  hooks:
    - go mod tidy

builds:
  - id: linux-builds
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    binary: "jp-cli"

  - id: windows-builds
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    binary: "jp-cli"
  
  - id: macos-builds
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    binary: "jp-cli"

archives:
  - format: tar.gz
    # This name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    
    # Use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nfpms:
  - id: linux-packages
    builds:
      - linux-builds
    vendor: JP
    homepage: https://github.com/joaopalet
    maintainer: JP <joao.palet@outlook.com>
    description: A command-line interface built by JP.
    license: Apache 2.0
    formats:
      - deb
      - rpm

# signs:
#   - artifacts: package
#     args: ["-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]

brews:
  - repository:
      owner: joaopalet
      name: homebrew-cli-test
    commit_author:
      name: joaopalet
      email: joao.palet@outlook.com
    homepage: "https://github.com/joaopalet/cli-test"
    description: "A test CLI built by JP"
    license: "Apache-2.0"
    skip_upload: auto
    folder: Formula

snapcrafts:
  - id: snap-packages
    # Build IDs for the builds you want to create snapcraft packages for.
    builds:
      - linux-builds
    # The name of the snap.
    name: jp-cli
    # The canonical title of the application, displayed in the software
    # centre graphical frontends.
    title: JP CLI
    # Whether to publish the snap to the snapcraft store.
    # Remember you need to `snapcraft login` first.
    publish: true
    # Single-line elevator pitch for your amazing snap.
    # 79 char long at most.
    summary: A test CLI built by JP.
    # This the description of your snap. You have a paragraph or two to tell the
    # most important story about your snap. Keep it under 100 words though,
    # we live in tweetspace and your description wants to look good in the snap
    # store.
    description: A test CLI built by JP. Trying to publish it to the Snapcraft store!
    license: Apache-2.0